#include "calculation_catalog.h"
#include <QStringList>

namespace CalculationCatalog {
bool Entry::isCompletion() const
{
    return kind == Kind::Function || kind == Kind::Constant;
}

bool Entry::matches(const QString &query, bool completion) const
{
    const QString needle = query.trimmed();
    if (needle.isEmpty()) return true;
    if (!completion)
        return (signature + QLatin1Char(' ') + category + QLatin1Char(' ') + title + QLatin1Char(' ') +
                description + QLatin1Char(' ') + example + QLatin1Char(' ') + keywords)
            .contains(needle, Qt::CaseInsensitive);
    if (name.startsWith(needle, Qt::CaseInsensitive) || title.contains(needle, Qt::CaseInsensitive)) return true;
    for (const QString &word : keywords.split(QLatin1Char(' '), Qt::SkipEmptyParts))
        if (word.startsWith(needle, Qt::CaseInsensitive)) return true;
    return false;
}

const QVector<Entry> &entries()
{
    static const QVector<Entry> values = {
        {Kind::Operator, QStringLiteral("+ -"), QStringLiteral("x + y；x - y"), QStringLiteral("基本运算"), QStringLiteral("加法与减法"), QStringLiteral("同级从左向右计算，优先级低于乘除和乘方。"), QStringLiteral("1+2*3 → 7"), QStringLiteral("加法 减法 四则 优先级 结合"), {}, 0},
        {Kind::Operator, QStringLiteral("* /"), QStringLiteral("x * y；x / y"), QStringLiteral("基本运算"), QStringLiteral("乘法与除法"), QStringLiteral("同级从左向右计算；除数不能为 0。×、÷ 也可使用。"), QStringLiteral("8/4/2 → 1"), QStringLiteral("乘法 除法 四则 除零"), {}, 0},
        {Kind::Operator, QStringLiteral("%"), QStringLiteral("x % y"), QStringLiteral("基本运算"), QStringLiteral("取余"), QStringLiteral("不是百分比；非零余数与被除数同号，除数不能为 0。十进制数在支持范围内精确取余；含近似值时，结果可能有浮点误差。"), QStringLiteral("-10%3 → -1；5.5%2 → 1.5"), QStringLiteral("取余 余数 模 百分比"), {}, 0},
        {Kind::Operator, QStringLiteral("^"), QStringLiteral("x ^ y"), QStringLiteral("基本运算"), QStringLiteral("乘方"), QStringLiteral("从右向左计算；优先级高于一元负号。负底数仅接受整数指数；底数为 0 时指数不能为负数，0^0 = 1。十进制整数幂的指数绝对值最多 10000；负整数幂先算正幂再取倒数，中间结果超出精度或范围时会报错。"), QStringLiteral("2^3^2 → 512；-2^2 → -4；2^-3 → 0.125"), QStringLiteral("乘方 幂 指数 优先级 结合"), {}, 0},
        {Kind::Operator, QStringLiteral("unary"), QStringLiteral("+x；-x；(x)"), QStringLiteral("基本运算"), QStringLiteral("正负号与括号"), QStringLiteral("括号改变运算顺序；支持连续正负号。乘法必须显式输入 *，不支持 2pi 或 2(3)。"), QStringLiteral("(-2)^2 → 4；--2 → 2"), QStringLiteral("括号 正号 负号 隐式乘法"), {}, 0},
        {Kind::Function, QStringLiteral("sqrt"), QStringLiteral("sqrt(x)"), QStringLiteral("基础函数"), QStringLiteral("平方根"), QStringLiteral("x 必须大于或等于 0。十进制数能精确开方且结果在支持范围内时，返回精确值；其他情况使用近似计算。输入已是近似值时，结果也保留近似计算标记。"), QStringLiteral("sqrt(9) → 3"), QStringLiteral("平方根 开方 root"), QStringLiteral("sqrt()"), 5},
        {Kind::Function, QStringLiteral("abs"), QStringLiteral("abs(x)"), QStringLiteral("基础函数"), QStringLiteral("绝对值"), QStringLiteral("返回 x 的绝对值。"), QStringLiteral("abs(-2) → 2"), QStringLiteral("绝对值 absolute"), QStringLiteral("abs()"), 4},
        {Kind::Function, QStringLiteral("sin"), QStringLiteral("sin(x)"), QStringLiteral("三角函数"), QStringLiteral("正弦"), QStringLiteral("参数使用弧度；角度可用 度数*pi/180 转换。"), QStringLiteral("sin(pi/2) → 1"), QStringLiteral("正弦 三角 弧度 角度 sine"), QStringLiteral("sin()"), 4},
        {Kind::Function, QStringLiteral("cos"), QStringLiteral("cos(x)"), QStringLiteral("三角函数"), QStringLiteral("余弦"), QStringLiteral("参数使用弧度；没有角度模式。"), QStringLiteral("cos(0) → 1"), QStringLiteral("余弦 三角 弧度 角度 cosine"), QStringLiteral("cos()"), 4},
        {Kind::Function, QStringLiteral("tan"), QStringLiteral("tan(x)"), QStringLiteral("三角函数"), QStringLiteral("正切"), QStringLiteral("参数使用弧度；不会单独识别 pi/2 等数学奇点，附近结果可能是很大的有限值。"), QStringLiteral("tan(0) → 0"), QStringLiteral("正切 三角 弧度 角度 tangent"), QStringLiteral("tan()"), 4},
        {Kind::Function, QStringLiteral("ln"), QStringLiteral("ln(x)"), QStringLiteral("对数与指数"), QStringLiteral("自然对数"), QStringLiteral("以 e 为底，x 必须大于 0；0 和负数会提示定义域错误。"), QStringLiteral("ln(e) → 1"), QStringLiteral("对数 自然对数 logarithm"), QStringLiteral("ln()"), 3},
        {Kind::Function, QStringLiteral("log"), QStringLiteral("log(x)"), QStringLiteral("对数与指数"), QStringLiteral("常用对数"), QStringLiteral("以 10 为底，x 必须大于 0；0 和负数会提示定义域错误。"), QStringLiteral("log(1000) → 3"), QStringLiteral("对数 常用对数 log10 logarithm"), QStringLiteral("log()"), 4},
        {Kind::Function, QStringLiteral("exp"), QStringLiteral("exp(x)"), QStringLiteral("对数与指数"), QStringLiteral("自然指数"), QStringLiteral("计算 e 的 x 次幂，使用近似计算。结果过大，或非零结果小到只能表示成 0 时，会提示超出数值范围。"), QStringLiteral("exp(0) → 1"), QStringLiteral("指数 自然指数 exponential"), QStringLiteral("exp()"), 4},
        {Kind::Function, QStringLiteral("floor"), QStringLiteral("floor(x)"), QStringLiteral("整数舍入"), QStringLiteral("向下取整"), QStringLiteral("返回不大于 x 的最大整数，负数也向负无穷方向取整。"), QStringLiteral("floor(-1.2) → -2"), QStringLiteral("取整 向下 舍入"), QStringLiteral("floor()"), 6},
        {Kind::Function, QStringLiteral("ceil"), QStringLiteral("ceil(x)"), QStringLiteral("整数舍入"), QStringLiteral("向上取整"), QStringLiteral("返回不小于 x 的最小整数。"), QStringLiteral("ceil(1.2) → 2"), QStringLiteral("取整 向上 舍入"), QStringLiteral("ceil()"), 5},
        {Kind::Function, QStringLiteral("round"), QStringLiteral("round(x)"), QStringLiteral("整数舍入"), QStringLiteral("最近整数舍入"), QStringLiteral("取最近整数，恰好在两个整数中间时向远离 0 的方向取整。这与除法保留 50 位有效数字时的舍入规则不同。"), QStringLiteral("round(1.5) → 2；round(-1.5) → -2"), QStringLiteral("取整 四舍五入 舍入"), QStringLiteral("round()"), 6},
        {Kind::Function, QStringLiteral("min"), QStringLiteral("min(x, y)"), QStringLiteral("二元函数"), QStringLiteral("较小值"), QStringLiteral("恰好需要两个参数，用英文逗号分隔。"), QStringLiteral("min(2,3) → 2"), QStringLiteral("最小 较小 比较 minimum"), QStringLiteral("min(, )"), 4},
        {Kind::Function, QStringLiteral("max"), QStringLiteral("max(x, y)"), QStringLiteral("二元函数"), QStringLiteral("较大值"), QStringLiteral("恰好需要两个参数，用英文逗号分隔。"), QStringLiteral("max(-2,-3) → -2"), QStringLiteral("最大 较大 比较 maximum"), QStringLiteral("max(, )"), 4},
        {Kind::Function, QStringLiteral("pow"), QStringLiteral("pow(底数, 指数)"), QStringLiteral("二元函数"), QStringLiteral("乘方函数"), QStringLiteral("与 ^ 使用相同的乘方规则；恰好需要两个参数，用英文逗号分隔。"), QStringLiteral("pow(2,10) → 1024"), QStringLiteral("乘方 幂 次方 power"), QStringLiteral("pow(, )"), 4},
        {Kind::Constant, QStringLiteral("pi"), QStringLiteral("pi"), QStringLiteral("常量与上次结果"), QStringLiteral("圆周率"), QStringLiteral("圆周率的近似值，显示为 3.1415926535897931。参与计算时会保留近似计算标记。"), QStringLiteral("sin(pi/2) → 1"), QStringLiteral("圆周率 派"), QStringLiteral("pi"), 2},
        {Kind::Constant, QStringLiteral("e"), QStringLiteral("e"), QStringLiteral("常量与上次结果"), QStringLiteral("自然常数"), QStringLiteral("自然常数的近似值，显示为 2.7182818284590451。与科学计数法中的 e 含义不同。"), QStringLiteral("ln(e) → 1"), QStringLiteral("自然常数 欧拉"), QStringLiteral("e"), 1},
        {Kind::Constant, QStringLiteral("ans"), QStringLiteral("ans"), QStringLiteral("常量与上次结果"), QStringLiteral("上一次成功结果"), QStringLiteral("初始为 0，保留上一次成功结果及其计算来源；失败计算不更新。清空会话或打开新的空白会话后重置为 0；恢复本地会话时保留已保存值。"), QStringLiteral("先计算 6*7，再计算 ans+1 → 43"), QStringLiteral("上次 上一次 结果 答案 answer"), QStringLiteral("ans"), 3},
        {Kind::Syntax, QStringLiteral("numbers"), QStringLiteral("小数与科学计数法"), QStringLiteral("输入语法"), QStringLiteral("数字写法"), QStringLiteral("小数点固定为 .，支持 .5、1. 和 e/E 指数，不接受千分位或全角数字。"), QStringLiteral("1e3+2.5E-2 → 1000.025"), QStringLiteral("数字 小数 科学计数法 区域设置"), {}, 0},
        {Kind::Syntax, QStringLiteral("input"), QStringLiteral("大小写、嵌套与输入限制"), QStringLiteral("输入语法"), QStringLiteral("公式规则"), QStringLiteral("函数和常量不区分大小写，可嵌套，运算符两侧可留空白。公式长度上限为 4096，普通英文字母、数字和运算符各计 1；嵌套过深时请拆分计算。普通模式不支持变量赋值；自定义公式通过底部模式菜单定义参数。不支持复数或符号求解。"), QStringLiteral("MAX(sqrt(9),pow(2,3)) → 8"), QStringLiteral("大小写 嵌套 长度 语法 错误 变量"), {}, 0},
        {Kind::Syntax, QStringLiteral("custom"), QStringLiteral("自定义公式与参数"), QStringLiteral("输入操作"), QStringLiteral("定义一次，填写不同参数后确认计算"), QStringLiteral("从底部模式菜单进入自定义公式，在参数区上方的公式定义栏直接输入 A=x+y，按 Enter 应用并生成 x=、y=；后续修改也在该栏按 Enter 确认。公式定义支持 @ 补全，候选打开时 Enter 先选中候选，再按 Enter 应用定义。Esc 还原已确认定义；首次定义时取消则返回普通模式。每行填写一个参数。名称只用英文字母、数字、下划线，不能以数字开头，区分大小写且不能与内置名称冲突。参数只填有符号数字、小数或科学计数法；公式支持全部函数、pi、e 和 ans。按 Ctrl+Enter 或点击“计算”后追加记录，成功后保留参数；编辑和普通 Enter 换行不会触发计算。未确认或无效的公式修改会阻止计算；缺少或非法参数不生成记录，数学错误保留错误记录。两种模式共享 ans，分别保留草稿；修改定义时保留同名参数值，新增参数留空。复用历史会恢复当时的定义和参数；成功提交、越过最新记录或手动切换模式后结束浏览并返回草稿。未确认的定义只在当前窗口保留，本地保存仍使用已确认定义；数值参数区不启用 @ 补全。"), QStringLiteral("A=x+y，分两行填 x=1 和 y=2；Ctrl+Enter 后显示 A=1+2，下一行 = 3"), QStringLiteral("自定义 参数 公式 模式 定义 保存 历史 变量"), {}, 0},
        {Kind::Syntax, QStringLiteral("diagnostics"), QStringLiteral("错误定位与修正"), QStringLiteral("输入操作"), QStringLiteral("标记问题字符或参数"), QStringLiteral("普通模式计算失败时保留公式和 ans，用底色与波浪线标记问题位置，光标移到问题处，并显示行列。末尾缺少内容时标记该行，光标停在需要补充的位置。标记不等于选中文字，继续输入不会替换整段。编辑、输入法组词或清空会话后移除标记，重新提交可再次定位；回填未修改的失败公式会恢复标记。自定义模式通过状态提示说明参数或计算错误，不在参数输入框中标记代入公式的位置。"), QStringLiteral("普通模式输入 ln(0)，标记参数 0；自定义 A=1/x、x=0，提示除数不能为 0，保留参数以便修正。"), QStringLiteral("错误 定位 高亮 范围 行列 参数 修正 下划线"), {}, 0},
        {Kind::Syntax, QStringLiteral("completion"), QStringLiteral("@ 快捷补全"), QStringLiteral("输入语法"), QStringLiteral("查找函数与常量"), QStringLiteral("普通公式输入和自定义公式定义栏支持 @，可用英文名称或中文关键词筛选；↑↓ 选择，Enter/Tab 插入，Esc 关闭。在定义栏补全后按 Enter 应用公式，再填写参数；普通公式或参数填写完成后，按 Ctrl+Enter 或点击“计算”。中文输入法组词时优先处理输入法候选。"), QStringLiteral("2+@平方根 → 2+sqrt()，光标位于括号内"), QStringLiteral("补全 快捷 输入法 帮助"), {}, 0},
        {Kind::Syntax, QStringLiteral("history"), QStringLiteral("Alt+↑ / Alt+↓ 历史召回"), QStringLiteral("输入操作"), QStringLiteral("保留草稿并浏览历史公式"), QStringLiteral("在输入框按 Alt+↑ 从最新记录向前浏览，Alt+↓ 向后浏览，越过最新记录返回草稿；最旧处不循环。首次召回保存草稿、光标和选区，本轮浏览中的临时编辑会保留；返回草稿或成功提交后结束浏览。普通方向键移动光标；输入法组词或 @ 候选可见时不召回。召回只回填内容，成功提交按当前 ans 追加计算并返回原草稿，失败保留待修正。“再次使用／修改公式”也保留草稿。切换历史记录后不能通过撤销恢复上一条输入；当前记录中的文字编辑仍可撤销。"), QStringLiteral("先计算 6*7，输入草稿 100+；Alt+↑ 召回并改为 6*7+1，Ctrl+Enter 得到 43 后回到 100+"), QStringLiteral("历史 召回 草稿 键盘 快捷键 Alt 上下 回填 编辑 撤销"), {}, 0},
        {Kind::Syntax, QStringLiteral("session"), QStringLiteral("本地会话保存与恢复"), QStringLiteral("输入操作"), QStringLiteral("可选保存记录、ans 与草稿"), QStringLiteral("默认不保存。通过“本地会话”选择新文件后自动保存记录、ans、两种模式的草稿、已确认的公式定义、参数和历史浏览位置，完整保留结果及计算来源。尚未按 Enter 应用的定义修改不保存。关闭后文件仍在；重开或重启后，从空白计算器选择“恢复会话…”，不会重新计算历史。每个文件同时只能由一个窗口或进程使用。清空会话也会更新保存文件；停止保存前会保存最后更改。保存失败时请在关闭前重试或另存。只支持当前第 3 版会话格式，旧格式、未知格式或损坏文件不会载入或覆盖。输入法未上屏文字和文字撤销记录不保存；单文件最多 16 MiB、10000 条记录。"), QStringLiteral("本地会话 → 开启保存；关闭标签 → 打开空白计算器 → 恢复会话"), QStringLiteral("保存 恢复 历史 文件 本地 会话 草稿 重启 自动 保存失败 重试"), {}, 0},
        {Kind::Syntax, QStringLiteral("clear"), QStringLiteral("清空会话"), QStringLiteral("输入操作"), QStringLiteral("重新开始当前窗口的计算"), QStringLiteral("点击顶部“清空会话”，确认后清空全部成功和失败记录，将 ans 重置为 0，编号从 01 开始。保留输入草稿、光标、选区和文字撤销记录；历史浏览中则返回召回前的草稿，丢弃本轮临时编辑。自定义公式及参数也会保留。确认框默认取消，Esc 或关闭也取消；清空记录不可撤销。其他窗口不受影响；没有记录或输入法组词期间按钮不可用。"), QStringLiteral("计算 42 后保留草稿 ans+1，清空会话再计算得到 1"), QStringLiteral("清空 会话 重置 删除 草稿 确认 取消 ans"), {}, 0},
        {Kind::Precision, QStringLiteral("double"), QStringLiteral("十进制与近似计算"), QStringLiteral("精度与限制"), QStringLiteral("最多 50 位十进制有效数字"), QStringLiteral("直接输入的数字按十进制计算，最多支持 50 位有效数字。十进制数的加、减、乘和取余在支持范围内精确计算，超限报错。三角函数、对数、exp、pi、e、非整数次幂和不能精确开方的平方根使用近似计算；含近似值的后续运算也使用近似计算。十进制结果完整显示，近似结果最多显示 17 位有效数字，但不保证每一位都准确。显示时，科学计数法指数在 -6 至 20 之间用普通小数，其余用小写 e；省略无意义的尾零，保留 -0。"), QStringLiteral("0.1+0.2 → 0.3；(0.1+0.2)-0.3 → 0"), QStringLiteral("精度 十进制 double binary64 来源 舍入 复制 负零 范围 下溢"), {}, 0},
        {Kind::Precision, QStringLiteral("integer"), QStringLiteral("整数与数值范围"), QStringLiteral("精度与限制"), QStringLiteral("数值与中间结果的限制"), QStringLiteral("最多支持 50 位有效数字，末尾用于表示数量级的零不占有效数字容量，例如 1000 只占 1 位。非零十进制数的科学计数法指数范围为 -999 至 999。每一步计算都要满足精度和范围限制，即使后续运算能抵消超限部分，也会先报错。十进制整数幂的指数绝对值最多 10000；负幂先算正幂再取倒数，因此 2^-200 会因中间正幂超过 50 位而失败。"), QStringLiteral("(1e16+1)-1e16 → 1；(1e50+1)-1e50 报精度超限"), QStringLiteral("精度 十进制 double binary64 来源 舍入 复制 负零 范围 下溢"), {}, 0},
        {Kind::Precision, QStringLiteral("underflow"), QStringLiteral("转换与下溢"), QStringLiteral("精度与限制"), QStringLiteral("过大或过小的数值"), QStringLiteral("最小正十进制数为 1e-999，超出十进制范围时会报错。sin、ln 等近似计算的数值范围更小，参数超出范围时提示转换上溢或下溢。能精确开方的十进制数仍按十进制范围处理。近似计算若检测到非零结果小到只能表示成 0，也会报错；仍能表示的极小非零值可以保留，但有效精度可能降低，最小约为 4.9406564584124654e-324。"), QStringLiteral("1e-200*1e-200 → 1e-400；sqrt(1e400) → 1e+200；ln(1e400) 报上溢；sin(1e-400) 和 exp(-1000) 报下溢。"), QStringLiteral("精度 十进制 double binary64 来源 舍入 复制 负零 范围 下溢 非正规数 次正规数"), {}, 0},
        {Kind::Precision, QStringLiteral("reuse"), QStringLiteral("ans、复制与插入结果数值"), QStringLiteral("精度与限制"), QStringLiteral("保留计算来源与重新输入的区别"), QStringLiteral("复制纯数值、选中结果数字复制或插入结果数值，得到的数字与显示一致。再次提交时按新输入的十进制数计算，不继承原结果的近似或舍入来源。使用 ans 或恢复会话可以保留完整数值及计算来源。普通模式插入负数带括号，自定义参数插入有符号数字；复制整条计算和导出记录会附上来源说明。"), QStringLiteral("先计算 sin(0)，再计算 ans+0.1 会保留近似计算标记；复制或插入数字 0 后计算 0+0.1，得到精确十进制 0.1。"), QStringLiteral("精度 十进制 double binary64 来源 舍入 复制 负零 范围 下溢"), {}, 0},
        {Kind::Precision, QStringLiteral("rounding"), QStringLiteral("除法舍入与计算来源"), QStringLiteral("精度与限制"), QStringLiteral("每次除法分别舍入"), QStringLiteral("每次十进制除法最多保留 50 位有效数字，先舍入再继续后续计算。能在 50 位内表示的有限小数商保持精确；有限小数商超过 50 位，或商为无限循环小数时，也需要舍入。舍入取最接近的值，恰好居中时让保留的最后一位为偶数。结果下方会显示“含除法舍入”“含近似计算”“含转换损失”；这些标记说明计算来源，不表示误差大小，也不会因结果为 0 或整数而消失。后续十进制加、减、乘仍需精确完成，超限时会报错。"), QStringLiteral("1/8 → 0.125；1/3 和 1/(2^100) 保留 50 位并提示舍入；(1/6)*6 的乘法结果超过 50 位，会报精度超限。"), QStringLiteral("精度 十进制 double binary64 来源 舍入 复制 负零 范围 下溢"), {}, 0},
        {Kind::Precision, QStringLiteral("domain"), QStringLiteral("定义域、弧度与数学奇点"), QStringLiteral("常见疑问"), QStringLiteral("有限结果不一定可靠"), QStringLiteral("三角函数使用弧度。pi 为近似值，所以 sin(pi) 可能约为 1.22e-16；tan(pi/2) 可能返回很大的有限数。sqrt 的参数须大于或等于 0，ln/log 的参数须大于 0，否则提示定义域错误。除数恰好为 0 时提示除零错误。错误定位方式见“错误定位与修正”。"), QStringLiteral("pow(-8,1/3) 不会被当作实数立方根 -2"), QStringLiteral("精度 正弦 弧度 度数 奇点 定义域 除零 对数"), {}, 0}
    };
    return values;
}
}
